FROM golang:1.12.5-alpine3.9 as debug

# installing git
RUN apk update && apk upgrade && \
    apk add --no-cache git \
        dpkg \
        gcc \
        git \
        musl-dev

RUN mkdir /app
COPY ./* /app/
WORKDIR /app/go_challenge

RUN go build *.go 

###########START NEW IMAGE###################

FROM alpine:3.9 as prod
COPY --from=debug /app/go_challenge/* /
CMD ./main
