name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${ secrets.DOCKER_USER }}
        DOCKER_PASSWD: ${ secrets.DOCKER_PASSWD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWD https://registry-1.docker.io/v2/
    - name: Build the Docker image
      run: docker build . --file ./golang/dockerfile --tag 23emre/main:action_v1
    - name: Push Docker image
      run: |
        dokce push 23emre/main:action_v1
